version: '3.8'

services:
  # --- Base de Datos ---
  mongodb:
    image: mongo:latest
    container_name: tutorias_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - tutorias-net

  # --- Backend ---
  backend:
    build: ./backend
    container_name: tutorias_backend
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MONGODB_URI=mongodb://mongodb:27017/tutorias_fis
      - JWT_SECRET=SecretKey_EPN_2026
      - FRONTEND_URL=http://localhost:3001
    depends_on:
      - mongodb
    networks:
      - tutorias-net

  # --- Frontend ---
  frontend:
    build:
      context: ./frontend
      args:
        # CORREGIDO: Se quitó el "/api" del final
        - NEXT_PUBLIC_API_URL=http://localhost:4000
    container_name: tutorias_frontend
    ports:
      - "3001:3001"
    environment:
      # CORREGIDO: Se quitó el "/api" del final
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    depends_on:
      - backend
    networks:
      - tutorias-net

  # --- Monitoreo (Prometheus) ---
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - tutorias-net

  # --- Visualización (Grafana) ---
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3002:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - tutorias-net

# --- Redes y Volúmenes (Nivel Raíz) ---
networks:
  tutorias-net:
    driver: bridge

volumes:
  mongo_data:
